name: AnyKernel3 Packager
description: Package kernel with AK3

inputs:
  image:
    required: true
  manager:
    required: true
  susfs:
    default: "no"
  bbg:
    default: "no"
  zip_name:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e

        IMAGE="${{ inputs.image }}"
        ZIP="${{ inputs.zip_name }}"

        test -f "$IMAGE" || exit 1

        FEATURES="${{ inputs.manager }}"
        [ "${{ inputs.susfs }}" = "yes" ] && FEATURES="${FEATURES}-susfs"
        [ "${{ inputs.bbg }}" = "yes" ] && FEATURES="${FEATURES}-bbg"

        rm -rf anykernel
        git clone --depth=1 https://github.com/DikyVinus/AnyKernel3 anykernel

        cp "$IMAGE" anykernel/Image

        sed -i "s|kernel.string=.*|kernel.string=CoreShift-${FEATURES}|g" anykernel/anykernel.sh

        cd anykernel

        zip -r9 "../$ZIP" ./*

        cd ..

        test -f "$ZIP" || exit 1
