name: Lite Tester (All Managers)

on:
  workflow_dispatch:
    inputs:
      susfs:
        required: true
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
      bbg:
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        manager: [ksu, ksun, kowsu, resukisu, vanilla]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare kernel tree (clone once)
        run: |
          set -e
          mkdir -p gki
          git clone --depth=1 --branch chihiro-rebase \
            https://github.com/MillenniumOSS/android_kernel_common_android12-5.10.git \
            gki/common

      - name: Save clean state
        working-directory: gki/common
        run: |
          set -e
          git add .
          git commit -m "clean state" || true

      - name: Reset tree
        working-directory: gki/common
        run: |
          set -e
          git reset --hard
          git clean -fdx

      - name: Setup Manager
        uses: ./.github/actions/setup-manager
        with:
          root_type: ${{ matrix.manager }}

      - name: Setup SUSFS
        if: ${{ github.event.inputs.susfs == 'yes' }}
        uses: ./.github/actions/setup-susfs

      - name: Setup BBG
        if: ${{ github.event.inputs.bbg == 'yes' }}
        uses: ./.github/actions/setup-bbg
